
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { PathName } from "@/ui/nav";
import { Footer } from "@/ui/footer";
import { getServerSession } from "next-auth";
import SessionProvider from "@/ui/authentiation";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({children,}: Readonly<{children: React.ReactNode;}>) {

  const session = await getServerSession()
  return (
    <html lang="en">
      <head>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" />
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>

        <SessionProvider 
          session={session}
          refetchInterval={60 * 60} // Refresh session every hour
          refetchOnWindowFocus={true}
        >       
          <main>
            <PathName/>
            {children}
            <Footer/>
          </main>
        </SessionProvider>  
         
      </body>
    </html>
  );
}
